server:
  port: 8084
  main:
    web-application-type: reactive
spring:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 10MB
  datasource:
    url: ${AIMALL_DB_URL:jdbc:mysql://localhost:3306/aimall?allowMultiQueries=true&useSSL=false&serverTimezone=GMT%2B8&characterEncoding=utf8}
    username: ${AIMALL_DB_USERNAME:root}
    password: ${AIMALL_DB_PASSWORD:}
    driver-class-name: com.mysql.cj.jdbc.Driver
  task:
    scheduling:
      pool:
        size: 5
  data:
    redis:
      host: 127.0.0.1
      port: 6379
  ai:
    # MCP 服务
    mcp:
      server:
        protocol: STREAMABLE # STREAMABLE STATELESS
        name: aimall-mcp  # 服务器名称
        version: 1.0.0
        streamable-http:
          mcp-endpoint: /mcp  #默认是mcp
          keep-alive-interval: 60s
mybatis:
  configuration:
    map-underscore-to-camel-case: true
#项目目录
project:
  folder: ${AIMALL_PROJECT_FOLDER:./data/aimall/}
#支付宝
alipay:
  appid: ${AIMALL_ALIPAY_APP_ID:}
  # 应用私钥
  appPrivateKey: ${AIMALL_ALIPAY_APP_PRIVATE_KEY:}
  appCertPath: alipay-sandbox/appPublicCert.crt
  alipayPublicCertPath: alipay-sandbox/alipayPublicCert.crt
  alipayRootCertPath: alipay-sandbox/alipayRootCert.crt
  serverUrl: ${AIMALL_ALIPAY_SERVER_URL:https://openapi-sandbox.dl.alipaydev.com/gateway.do}
